version: '3.8'
services:
  frontend:
    image: node:16
    volumes:
      - ./frontend/dockernext:/frontend/dockernext
    working_dir: /frontend/dockernext
    ports:
      - '3000:3000'
    command: sh -c "yarn install && yarn dev"

  php:
    image: php:7.4-fpm
    volumes:
      - ./backend:/var/www/html
    
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
